jobs:
  include:
# -----------------------------------------------
# Linux amd64
# -----------------------------------------------

  - name: Linux amd64 - Go 1.12.x
    os: linux
    dist: xenial
    sudo: true
    language: go
    go: 1.12.x
    cache:
      directories:
      - "$HOME/.cache/go-build"
      - "$HOME/gopath/pkg"
    script:
    - export GOOS=linux
    - export GOARCH=amd64
    - export CGO_ENABLED=1
    - make all

# -----------------------------------------------
# Linux i386
# -----------------------------------------------

  - name: Linux i386 - Go 1.12.x
    os: linux
    dist: xenial
    sudo: true
    language: go
    go: 1.12.x
    cache:
      directories:
      - "$HOME/.cache/go-build"
      - "$HOME/gopath/pkg"
    addons:
      apt:
        packages:
          - gcc-multilib
          - gccgo-multilib
    script:
    - export GOOS=linux
    - export GOARCH=386
    - export CGO_ENABLED=1
    - make all
      #
# -----------------------------------------------
# Linux armhf
# -----------------------------------------------

  - name: Linux armhf - Go 1.12.x
    os: linux
    dist: xenial
    sudo: true
    language: go
    go: 1.12.x
    cache:
      directories:
      - "$HOME/.cache/go-build"
      - "$HOME/gopath/pkg"
    addons:
      apt:
        packages:
          - gcc-arm-linux-gnueabihf
          - gccgo-arm-linux-gnueabihf
    script:
    - export GOOS=linux
    - export GOARCH=arm
    - export GOARM=7
    - export CGO_ENABLED=1
    - export GCCGO=arm-linux-gnueabihf-gcc
    - export CC=arm-linux-gnueabihf-gccgo
    - make all

# -----------------------------------------------
# Linux arm64
# -----------------------------------------------

  - name: Linux arm64 - Go 1.12.x
    os: linux
    dist: xenial
    sudo: true
    language: go
    go: 1.12.x
    cache:
      directories:
      - "$HOME/.cache/go-build"
      - "$HOME/gopath/pkg"
    addons:
      apt:
        packages:
          - gcc-aarch64-linux-gnu
          - gccgo-aarch64-linux-gnu
    script:
    - export GOOS=linux
    - export GOARCH=arm64
    - export CGO_ENABLED=1
    - export GCCGO=aarch64-linux-gnu-gccgo
    - export CC=aarch64-linux-gnu-gcc
    - make all

