os: linux
language: c
sudo: required

services:
  - docker

env:
  global:
  - AWS_S3_BUCKET=dl.kuzzle.io
  - AWS_CLOUDFRONT_DISTRIBUTION_ID=E12YL8EZVABYR0
  # AWS ACCESS KEY ID
  - secure: "aqnEqyjGjrr8xjMl+hVuV3rFHezb7UD9/yiN3099ZaHp7jGOZD7OGbaOKFiG6p5FFa19iAsiAkhVIeZfQbzy2F4ReUfEx4yLlpHhS/8ABvpUC3hto732heJKKmfyaKuku2vqXanQ+tH1eNKqhySSxXrzNdIQt+TeFyviqcTSXo6NQvdq7yWOF0vZekdvA6ZMGsfkDDiWSITEd5YgxU7Zadw9QoMs6CnY2XC9YQ4VZxgnyG9SAIX915n2u59TGAUkj1cbGUT4MP683EwXxFWD0JUNyb9HbgNq9tvgndytlTWzJaL5eUWXdz0+ARxXl3VFVTKxrAwUlcFT1BiZl365GhswTg36xigluSLl0fpJTQ7+oKJ9zPbrb8u6qY2YrxC9t/rIqu3RbWRtkPDQXCn7Cr+MdCFYjlag/bO/9Ruf1LCGkuq2roUlWOs2tjhfbokXqUXUcDglXbIutKnfqyjTz1Iny8O5xUeMJO6Ms//Dxqb4eH6rKIllAPMdEqZJvZTW15r9IgY/pSdN7yK14yqQ+oinJNDRwfhXztdPGs7pAsFih+iaeQ8YnXsJywtWXX0skIo7sSnxOfANzqbXmoMOaN1T6tZF4ByRX28TOLkucXqNsS1WUmEwM1APM2Rl+eE/HpEKUAkR4mShSx7LvQ8yOWN8loIWfdNqzyHges6TjBM="
  # AWS SECRET ACCESS KEY
  - secure: "elX7qqlJaJ8fHr8bTSkLlhsf5GAd73HjCvb4FbgbwxVCQF3ghiHTZF06GSOSFgKtTvN2KP5KKd9jq9xGlGcolTi5BcEB0L62Cn7JYuMx1N7V3vsPfBiMkSkbEXZ1Fc3NiYazsnaanxjNZTeXjYRSJ7oKfPDEgbGRESkGEPLLxtuF+OWl32v7aPIkLxIM6KFwh0kTJNP9oWr/t26peSAORpO9nU8ots2JzuHdWFUIGZP2McOQM4uLhj3bDrl0Nch/ZFX9XVrvvhurg41e4DYHFBusUgm6RM664JehqyMhsZly+Hch7gx8H1EKqlVVOhbkyD+5PclQVdQKGbZKb9PioUSzI7tW0nZNs5YmSgcB9jwpC3CB4aQobpoZmMZVXNLAltWmPe1HEWOAJK1hHi35yhXMzO6B1OA1OKIJQnPgwKWEUpXUoTLGkfwQuiTr+1ue1GR8j6J41B+Hyb2em5ylCF6tWcR4hxfG+2Ag7IUVtRdwaEpTmqqxV/F7zhr+Kn+j0bJUE7318CH+3ax+T/FkApeyTIAuPhdJ9QWWHDxPGor1yXcuZTFZM3OF/pQH00FxvazNhlSI4gYkFXmmWIfqr4gYtQO15nD7mmR0J/RMUzU+4p6ZZyAfI0BYKYe4sW3HPjgybkEseyDG9zJxrg2508Fi1yZsyl4G81Pb4DrtmgI="

addons:
  apt:
    packages:
    - python
    - python-pip

install:
  - pip install awscli --upgrade --user

before_deploy:
  - docker run --rm -it -v "$(pwd)":/mnt kuzzleio/sdk-cross:gcc make package

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_S3_BUCKET
  region: us-west-2
  skip_cleanup: true
  upload-dir: sdk/c/$TRAVIS_BRANCH
  local-dir: deploy
  on:
    all_branches: true
    condition: branch = master OR branch =~ ^.?-dev$

after_deploy:
  - aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_DISTRIBUTION_ID --paths "/*"

matrix:
  include:
# ---------------------------------------------
# AMD64: Build and deploy (only on master)
# ---------------------------------------------
    - env:
        - ARCH="amd64"

      script:
        # Build
        - docker run --rm -it -v "$(pwd)":/mnt kuzzleio/sdk-cross:gcc make

# ---------------------------------------------
# I386: Build and deploy (only on master)
# ---------------------------------------------
    - env:
        - ARCH="i386"

      script:
        # Build
        - docker run --rm -it -v "$(pwd)":/mnt kuzzleio/sdk-cross:gcc-i386 make

# ---------------------------------------------
# ARMV7: Build and deploy (only on master)
# ---------------------------------------------
    - env:
        - ARCH="armhf"

      script:
        # Build
        - docker run --rm -it -v "$(pwd)":/mnt kuzzleio/sdk-cross:gcc-armhf make

# ---------------------------------------------
# ARMV8: Build and deploy (only on master)
# ---------------------------------------------
    - env:
         - ARCH="aarch64"

      script:
        # Build
        - docker run --rm -it -v "$(pwd)":/mnt kuzzleio/sdk-cross:gcc-aarch64 make

